version: "3"

name: music-service

services:
  music-service.frontend:
    container_name: music-service.frontend
    image: music-service.frontend
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    restart: no
    ports:
      - "8080:80"
    depends_on:
      - music-service.webapi
  
  music-service.webapi:
    container_name: music-service.webapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5555"
    image: music-service.webapi
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: MusicService.WebApi/Dockerfile
    restart: no