version: "3"

name: music-service

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - music-service.frontend
      - music-service.webapi
    networks:
      - dev

  music-service.frontend:
    container_name: music-service.frontend
    image: music-service.frontend
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - music-service.webapi
    networks:
      - dev
  
  music-service.webapi:
    container_name: music-service.webapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5555"
    image: music-service.webapi
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: MusicService.WebApi/Dockerfile
    networks:
      - dev