version: "3"

name: music-service
volumes:
  db.data:
  data-protection-keys:

networks:
  dev:

services:
  frontend:
    container_name: music-service.frontend
    image: music-service.frontend
    build:
      context: ./clients/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - data-protection-keys:/app/data-protection-keys
    depends_on:
      - webapi
    networks:
      - dev
  
  webapi:
    container_name: music-service.webapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "5555"
    image: music-service.webapi
    ports:
      - "5555:5555"
    build:
      context: .
      dockerfile: MusicService.WebApi/Dockerfile
    networks:
      - dev